#!/usr/bin/bash -xe

# d:
#   bun run dev

# t/:
#   table:
#     bun test src/lib/json-to-table.test.ts
#   bun test

# b:
#   # build (no --bun, conflict with vite)
#   bun run build

# deploy: b
#   # navigate into the build output directory
#   cd dist
#   # place .nojekyll to bypass Jekyll processing
#   echo > .nojekyll
#   # if you are deploying to a custom domain
#   # echo 'www.example.com' > CNAME
#   git init
#   git checkout -B main
#   git add -A
#   git commit -m 'deploy'
#   # if you are deploying to https://<USERNAME>.github.io
#   # git push -f git@github.com:<USERNAME>/<USERNAME>.github.io.git main
#   # if you are deploying to https://<USERNAME>.github.io/<REPO>
#   git push -f git@github.com:x0k/json-to-table.git main:gh-pages
#   cd -

w/:
  pushd web
  d:
    npm run dev
  c:
    npm run check
  popd
